const environmentVariables = require("../environmentVariables");
const UrlModel = require("../models/urlModel");
const asyncHandler = require("../utils/asyncHandler");
const CustomError = require("../utils/CustomError");
const { nanoid } = require("nanoid"); // npm package for genarating short unique ids.

// Generate New Short URL
module.exports.generateNewShortUrl = asyncHandler(async (req, res, next) => {
	const { url } = req.body;
	const { user } = req;
	if (!url) {
		return next(new CustomError("URL is missing!!", 400));
	}

	// generate short id
	// using `nano id` npm package to generate short unique ids.
	const shortId = nanoid(8); // this will generate a unique id of length 8.

	// create a new URL inside our database.
	const urlDoc = await UrlModel.create({
		createdBy: user._id,
		originalUrl: url,
		shortId: shortId,
		shortenUrl: `https://url-shortener-backend-yzcs.onrender.com/${shortId}`,
		visitHistory: [],
	});

	// send a response back to the client.
	return res.status(200).json({
		status: "success",
		message: "URL shortened successfully!",
		shortenUrl: urlDoc.shortenUrl,
		originalUrl: urlDoc.originalUrl,
	});
});

// Function to handle what to do when a user visits any particular shorten URL.
module.exports.redirectUserToOriginalUrl = asyncHandler(
	async (req, res, next) => {
		const shortId = req.params.shortId;

		// find the document with the given shortId.
		const urlDoc = await UrlModel.findOneAndUpdate(
			{ shortId: shortId },
			{
				$push: {
					visitHistory: {
						timestamp: Date.now(),
					},
				},
			}
		);

		if (!urlDoc) {
			return next(new CustomError("Invalid URL!!", 400));
		}

		// if the document exists, then redirect the user to the original URL.
		return res.status(200).redirect(urlDoc.originalUrl);
	}
);

// Get all URLs generate by any particulat user.
module.exports.getAllUrls = asyncHandler(async (req, res, next) => {
	// extract the user for the request body.
	const { user } = req;

	// fetch all the urls generated by the user.
	const urls = await UrlModel.find({ createdBy: user._id });

	return res.status(200).json({
		status: "success",
		message: urls ? "URLs fetched successfully!" : "No URLs found.",
		urls,
	});
});

// Get the most recently generate URL by any particular user.
module.exports.getRecentUrl = asyncHandler(async (req, res, next) => {
	// extract the user for the request body.
	const { user } = req;

	// Fetch the most recent URL created by the user.
	const recentUrl = await UrlModel.find({ createdBy: user._id })
		.sort({ createdAt: -1 }) // sort the documents in descending order (latest first)
		.limit(1); // fetch only one document

	return res.status(200).json({
		status: "success",
		message: recentUrl
			? "Most recent URL fetched successfully!"
			: "No URLs found.",
		recentUrl,
	});
});
